[package]
name = "opendeck"
version = "2.0.0"
description = "A cross-platform desktop application for ProntoKey and Stream Deck."
authors = [ "ninjadev64" ]
license = "BSD-3-Clause"
repository = "https://github.com/ninjadev64/OpenDeck"
default-run = "opendeck"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
# Large, fundamental libraries
tauri = { version = "1.5.2", features = [ "shell-execute", "shell-open", "system-tray", "devtools" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serialport = "4.2.2"
tokio = { version = "1.34.0", features = [ "full" ] }
tokio-tungstenite = "0.20.1"
tiny_http = "0.12.0"
elgato-streamdeck = { version = "0.5.0", default-features = false, features = [ "async" ] }
hidapi = { version = "2.5.0", default-features = false, features = [ "linux-static-hidraw", "macos-shared-device", "windows-native" ] }
image = { version = "0.24.6", default-features = false, features = [ "bmp", "jpeg" ] }
# Smaller utility libraries
futures-util = "0.3.29"
anyhow = "1.0.75"
log = "0.4.20"
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde-inline-default = "0.1.1"
serde_with = "3.4.0"
lazy_static = "1.4.0"
os_info = "3.7.0"
urlencoding = "2.1.3"
base64 = "0.21.7"

[features]
custom-protocol = [ "tauri/custom-protocol" ]
