[package]
name = "opendeck"
version = "2.0.0"
description = "A cross-platform desktop application for ProntoKey and Stream Deck."
authors = [ "ninjadev64" ]
license = "BSD-3-Clause"
repository = "https://github.com/ninjadev64/OpenDeck"
default-run = "opendeck"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "1.5.2", features = [ "system-tray", "api-all" ] }

[features]
custom-protocol = [ "tauri/custom-protocol" ]
